title: Welcome
description: My Personal Stack Problems
author: Jorge Espinoza Abud
github: https://github.com/jfreek
about: Me dedico a resolver problemas usando matemáticas, programación y tecnologías de inteligencia artificial.
disqus_shortname: personalweb
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/face.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/jorge-espinoza-abud/"
    - icon: fa-medium
      link: "https://medium.com/@jorgee.abud"
    - icon: fa-youtube
      link: "https://www.youtube.com/channel/UCwas1KORUMPptD5WEMbIhow"
    - icon: fa-github
      link: "https://github.com/jfreek"
    - icon: fa-facebook
      link: "https://www.facebook.com/jorgeeabud"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://jfreek.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
