# Site settings
title: Jorge Espinoza
email: jorge@misfitslab.com
url: https://jabud.tech
description: "Hi, my name is Jorge Espinoza and I solve problems using math, code and data."
keywords: "freelance, freelancer, machine learning, data scientist, web scraping, data engineer, big data, analytics"
skills: "Python Developer - Data Scientist - Data Engineer"
meta_author: Jorge Espinoza

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 424ef7 #80B3FF
  primary-rgb: "66, 78, 247" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jorge Espinoza
  location: Location
  social: Around the Web
  credits: Contact Me

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/jorge-espinoza-abud/
  - title: medium-m
    url: https://medium.com/@jorgee.abud
  - title: youtube
    url: https://www.youtube.com/channel/UCwas1KORUMPptD5WEMbIhow
  - title: github
    url: https://github.com/jfreek
  - title: facebook
    url: https://www.facebook.com/jorgeeabud

# Postal address (add as many lines as necessary)
address:
  - line: México

# Credits content
credits: 'Lets build great things together.'

# Build settings
markdown: kramdown
permalink: pretty
